"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Activity, Bell, CalendarDays, CheckSquare, FileBarChart, LayoutDashboard, Link2, Menu, Settings, ShieldCheck, Users, X } from "lucide-react";
import { useState } from "react";
import { cn } from "@/lib/utils";
import { useWorkspace } from "@/components/workspace-provider";
const links=[["Overview","/dashboard",LayoutDashboard],["Meetings","/meetings",CalendarDays],["Tasks","/tasks",CheckSquare],["Approvals","/approvals",ShieldCheck],["People","/people",Users],["Analytics","/analytics",Activity],["Integrations","/integrations",Link2],["Reports","/reports",FileBarChart],["Settings","/settings",Settings]] as const;
export function AppShell({children}:{children:React.ReactNode}){const path=usePathname(),[open,setOpen]=useState(false),{me,workspace,selectWorkspace}=useWorkspace();const nav=<nav className="space-y-1">{links.map(([label,href,Icon])=><Link onClick={()=>setOpen(false)} key={href} href={href} className={cn("flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition",path===href?"bg-white/[.09] text-white":"text-zinc-500 hover:bg-white/[.045] hover:text-zinc-200")}><Icon size={17}/>{label}</Link>)}</nav>;const initials=(me?.name??"?").split(" ").map(x=>x[0]).join("").slice(0,2);return <div className="min-h-screen bg-[#09090b] text-white"><aside className={cn("fixed inset-y-0 z-40 w-[250px] border-r border-white/[.08] bg-[#0d0d10] p-4 transition-transform lg:translate-x-0",open?"translate-x-0":"-translate-x-full")}><div className="flex items-center justify-between px-2"><Link href="/dashboard" className="flex items-center gap-2.5 font-semibold"><span className="grid h-8 w-8 place-items-center rounded-[10px] bg-emerald-300 font-black text-zinc-950">C</span>CloseLoop</Link><button className="lg:hidden" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="mt-8">{nav}</div><div className="absolute bottom-5 left-4 right-4 rounded-2xl border border-white/[.08] bg-white/[.035] p-3"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-full bg-gradient-to-br from-violet-500 to-orange-300 text-[10px] font-bold">{initials}</span><div><p className="text-xs font-medium">{me?.name??"Loading account"}</p><p className="text-[10px] text-zinc-500">{workspace?.name??"No workspace"}</p></div></div></div></aside>{open&&<button aria-label="Close menu" className="fixed inset-0 z-30 bg-black/60 lg:hidden" onClick={()=>setOpen(false)}/>}<main className="lg:ml-[250px]"><header className="flex h-[70px] items-center justify-between border-b border-white/[.08] px-5 lg:px-8"><button className="text-zinc-400 lg:hidden" onClick={()=>setOpen(true)}><Menu size={20}/></button><select value={workspace?.id??""} onChange={e=>selectWorkspace(e.target.value)} className="hidden rounded-lg border border-white/[.08] bg-[#111116] px-2 py-1 text-sm text-zinc-300 lg:block">{me?.workspaces.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><div className="ml-auto flex items-center gap-3"><button className="relative grid h-9 w-9 place-items-center rounded-xl border border-white/[.08] bg-white/[.035] text-zinc-400"><Bell size={16}/></button><Link href="/settings" className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-300 text-zinc-950"><Settings size={16}/></Link></div></header>{children}</main></div>}
