"use client";

import { useState } from "react";
import { api } from "@/lib/api";
import { useApi } from "@/hooks/use-api";
import { useWorkspace } from "@/components/workspace-provider";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
type Candidate={id:string;title:string;description:string|null;owner:string|null;deadline:string|null;confidence:number;evidence:unknown;state:string;task_id:string|null};
export function ApprovalQueue() { const { workspaceId,me } = useWorkspace(); const q = useApi<Candidate[]>(workspaceId ? `/task-candidates/workspace/${workspaceId}` : ""); const [busy,setBusy] = useState<string>(); const review = async (candidate:Candidate, decision:"approve"|"reject") => { if (!me) return; setBusy(candidate.id); try { await api(`/task-candidates/${candidate.id}/review`, {method:"POST",body:JSON.stringify({reviewer_id:me.id,decision})}); await q.reload(); } finally { setBusy(undefined); } }; return <main className="p-5 lg:p-8"><p className="text-xs font-medium tracking-[.16em] text-emerald-300">HUMAN REVIEW</p><h1 className="mt-2 text-3xl font-semibold">Task approvals</h1><p className="mt-2 text-sm text-zinc-500">Only lower-confidence extracted commitments require a decision.</p><div className="mt-7 grid gap-4">{q.loading ? <Card className="p-6 text-sm text-zinc-500">Loading candidates…</Card> : q.error ? <Card className="p-6 text-sm text-rose-200">{q.error}</Card> : q.data?.filter(x => x.state === "pending").map(candidate => <Card key={candidate.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-medium">{candidate.title}</p><p className="mt-1 text-sm text-zinc-400">{candidate.description}</p><p className="mt-3 text-xs text-zinc-500">Owner: {candidate.owner ?? "Unassigned"} · Deadline: {candidate.deadline ? new Date(candidate.deadline).toLocaleDateString() : "Not specified"}</p></div><p className="rounded-full bg-amber-300/10 px-3 py-1 text-xs text-amber-200">{Math.round(candidate.confidence * 100)}% confidence</p></div><pre className="mt-4 whitespace-pre-wrap rounded-xl bg-black/20 p-3 text-xs text-zinc-500">{JSON.stringify(candidate.evidence, null, 2)}</pre><div className="mt-4 flex gap-2"><Button size="sm" disabled={busy === candidate.id} onClick={() => void review(candidate,"approve")}>Approve</Button><Button size="sm" variant="danger" disabled={busy === candidate.id} onClick={() => void review(candidate,"reject")}>Reject</Button></div></Card>) ?? <Card className="p-6 text-sm text-zinc-500">No extracted tasks need review.</Card>}</div></main>; }
