"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, RefreshCw } from "lucide-react";
import { api } from "@/lib/api";
import { useApi } from "@/hooks/use-api";
import { useWorkspace } from "@/components/workspace-provider";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

type MeetingDetail = { id:string; title:string; provider:string; status:string; transcript_id:string|null; extraction:{status:string;summary:string|null;confidence:number|null;result:Record<string, unknown>|null;error:string|null}|null; chunks:{id:string;text:string;started_ms:number|null;ended_ms:number|null}[] };
type TaskDetail = { id:string;title:string;description:string|null;state:string;due_at:string|null;execution_score:number;evidence:unknown;dependencies:string[];github_matches:{activity_id:string;confidence:number;reason:string}[];external_refs:unknown };
function Loading({ error }: { error?:string }) { return <Card className="p-8 text-sm text-zinc-500">{error ?? "Loading…"}</Card>; }
function Values({ title, value }: { title:string; value:unknown }) { if (!value || (Array.isArray(value) && !value.length)) return null; return <Card className="p-5"><p className="text-sm font-medium capitalize">{title.replaceAll("_", " ")}</p><pre className="mt-3 whitespace-pre-wrap text-xs leading-5 text-zinc-400">{typeof value === "string" ? value : JSON.stringify(value, null, 2)}</pre></Card>; }
export function MeetingDetailPage({ meetingId }: { meetingId:string }) { const { workspaceId } = useWorkspace(); const q = useApi<MeetingDetail>(workspaceId ? `/workspaces/${workspaceId}/meetings/${meetingId}` : ""); const [extracting,setExtracting] = useState(false); const extract = async () => { if (!q.data?.transcript_id) return; setExtracting(true); try { await api(`/transcripts/${q.data.transcript_id}/extract`, {method:"POST"}); await q.reload(); } finally { setExtracting(false); } }; if (!q.data) return <main className="p-5 lg:p-8"><Loading error={q.error}/></main>; const data = q.data; const result = data.extraction?.result ?? {}; return <main className="p-5 lg:p-8"><Link href="/meetings" className="inline-flex items-center gap-2 text-sm text-zinc-500 hover:text-white"><ArrowLeft size={15}/>Meetings</Link><div className="mt-6 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.14em] text-emerald-300">{data.provider.replace("_", " ")} · {data.status}</p><h1 className="mt-2 text-3xl font-semibold">{data.title}</h1></div>{data.transcript_id && !data.extraction && <Button disabled={extracting} onClick={() => void extract()}><RefreshCw size={15}/>{extracting ? "Extracting…" : "Run extraction"}</Button>}</div>{data.extraction?.error && <Card className="mt-6 border-rose-400/20 p-4 text-sm text-rose-200">Extraction failed: {data.extraction.error}</Card>}<div className="mt-6 grid gap-4 lg:grid-cols-2"><Values title="Meeting summary" value={data.extraction?.summary}/><Values title="Decisions" value={result.decisions}/><Values title="Tasks and action items" value={result.tasks ?? result.action_items}/><Values title="Risks" value={result.risks}/><Values title="Questions" value={result.questions}/></div><Card className="mt-6"><div className="border-b border-white/[.08] p-5"><p className="font-medium">Transcript</p><p className="mt-1 text-xs text-zinc-500">Stored incrementally from Recall.</p></div><div className="divide-y divide-white/[.06]">{data.chunks.length ? data.chunks.map(chunk => <p key={chunk.id} className="p-5 text-sm leading-6 text-zinc-300">{chunk.text}</p>) : <p className="p-5 text-sm text-zinc-500">Transcript is not available yet.</p>}</div></Card></main>; }
export function TaskDetailPage({ taskId }: { taskId:string }) { const { workspaceId } = useWorkspace(); const q = useApi<TaskDetail>(workspaceId ? `/workspaces/${workspaceId}/tasks/${taskId}` : ""); if (!q.data) return <main className="p-5 lg:p-8"><Loading error={q.error}/></main>; const task = q.data; return <main className="p-5 lg:p-8"><Link href="/tasks" className="inline-flex items-center gap-2 text-sm text-zinc-500 hover:text-white"><ArrowLeft size={15}/>Tasks</Link><div className="mt-6"><p className="text-xs uppercase tracking-[.14em] text-emerald-300">{task.state} · score {Math.round(task.execution_score)}</p><h1 className="mt-2 text-3xl font-semibold">{task.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-400">{task.description ?? "No description provided."}</p></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><Values title="Evidence" value={task.evidence}/><Values title="Dependencies" value={task.dependencies}/><Values title="GitHub activity matches" value={task.github_matches}/><Values title="External references" value={task.external_refs}/></div></main>; }
