"use client";

import Link from "next/link";
import { useState } from "react";
import { CalendarClock, FileText, RefreshCw } from "lucide-react";
import { api } from "@/lib/api";
import { useApi } from "@/hooks/use-api";
import { useWorkspace } from "@/components/workspace-provider";
import { MeetingCreateDialog, TaskCreateDialog } from "@/components/workspace-actions";
import type { Insight, Integration, Meeting, Overview, Person, Report, Task } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

const title: Record<string, [string, string, string]> = { overview:["EXECUTION PULSE","Your team is moving with purpose.","Live data from meetings, tasks, and connected tools."], meetings:["MEETING INTELLIGENCE","Every conversation, accountable.","Recorded meetings and their execution trail."], tasks:["EXECUTION","Work that moves the business.","Prioritized by risk, ownership, and recent activity."], people:["PEOPLE","Capacity without surveillance.","Directory people receive messages but never dashboard access by default."], analytics:["ANALYTICS","Learn where execution slows.","Confidence-scored insights from your workspace."], integrations:["INTEGRATIONS","Your execution signal layer.","Connect only the tools your team uses."], reports:["REPORTS","A weekly operating rhythm.","Friday summaries for workspace owners and administrators."], settings:["SETTINGS","Workspace controls.","Owner and administrator settings."] };
function Header({ page, action }: { page:string; action?:React.ReactNode }) { const [eyebrow, heading, copy] = title[page]; return <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-[11px] font-medium tracking-[.16em] text-emerald-300">{eyebrow}</p><h1 className="mt-2 text-2xl font-semibold tracking-tight md:text-3xl">{heading}</h1><p className="mt-2 text-sm text-zinc-500">{copy}</p></div>{action}</div>; }
function State({ error, loading, empty }: { error?:string; loading:boolean; empty:string }) { if (loading) return <Card className="p-8 text-sm text-zinc-500">Loading workspace data…</Card>; if (error) return <Card className="border-amber-300/20 p-8 text-sm text-amber-100"><p className="font-medium">Unable to load this workspace</p><p className="mt-2 text-zinc-500">{error}</p><p className="mt-4 text-xs text-zinc-600">Sign in, then select a workspace from the header.</p></Card>; return <Card className="p-8 text-sm text-zinc-500">{empty}</Card>; }
function TaskRows({ tasks }: { tasks:Task[] }) { if (!tasks.length) return <p className="p-6 text-sm text-zinc-500">No tasks yet.</p>; return <div className="divide-y divide-white/[.06]">{tasks.map(task => <Link href={`/tasks/${task.id}`} key={task.id} className="flex items-center gap-3 px-5 py-4 transition hover:bg-white/[.03]"><i className={`h-2 w-2 rounded-full ${task.state === "blocked" ? "bg-rose-400" : task.state === "overdue" ? "bg-amber-300" : "bg-emerald-300"}`}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{task.title}</p><p className="mt-1 text-xs text-zinc-500">{task.due_at ? new Date(task.due_at).toLocaleDateString() : "No deadline"} · {task.state}</p></div><span className="text-sm text-emerald-300">{Math.round(task.execution_score)}</span></Link>)}</div>; }
function OverviewPage() { const { workspaceId } = useWorkspace(); const q = useApi<Overview>(workspaceId ? `/workspaces/${workspaceId}/overview` : ""); if (!q.data) return <><Header page="overview"/><State {...q} empty="No execution data yet."/></>; const d = q.data; return <><Header page="overview"/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Execution score",d.execution_score],["On-track work",`${d.on_track} / ${d.task_count}`],["Meetings",d.meetings],["At risk",d.at_risk]].map(([label,value]) => <Card key={String(label)} className="p-5"><p className="text-sm text-zinc-500">{label}</p><p className="mt-4 text-3xl font-semibold">{value}</p></Card>)}</div><Card className="mt-6"><div className="border-b border-white/[.08] p-5"><p className="font-medium">Execution radar</p></div><TaskRows tasks={d.tasks}/></Card></>; }
function MeetingsPage() { const { workspaceId } = useWorkspace(); const q = useApi<Meeting[]>(workspaceId ? `/workspaces/${workspaceId}/meetings` : ""); return <><Header page="meetings" action={<MeetingCreateDialog onCreated={q.reload}/>}/>{q.data ? <div className="grid gap-4">{q.data.map(m => <Link href={`/meetings/${m.id}`} key={m.id}><Card className="flex items-center gap-4 p-5 transition hover:bg-white/[.03]"><CalendarClock className="text-violet-300"/><div className="flex-1"><p className="font-medium">{m.title}</p><p className="mt-1 text-xs text-zinc-500">{m.provider.replace("_", " ")} · {m.status}</p></div><span className="text-xs text-zinc-500">{m.started_at ? new Date(m.started_at).toLocaleDateString() : "Scheduled"}</span></Card></Link>)}</div> : <State {...q} empty="No meetings captured yet."/>}</>; }
function TasksPage() { const { workspaceId } = useWorkspace(); const q = useApi<Task[]>(workspaceId ? `/workspaces/${workspaceId}/tasks` : ""); return <><Header page="tasks" action={<TaskCreateDialog onCreated={q.reload}/>}/><Card>{q.data ? <TaskRows tasks={q.data}/> : <State {...q} empty="No tasks exist in this workspace."/>}</Card></>; }
function PeoplePage() { const { workspaceId } = useWorkspace(); const q = useApi<Person[]>(workspaceId ? `/workspaces/${workspaceId}/people` : ""); return <><Header page="people"/>{q.data ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{q.data.map(p => <Card key={p.id} className="p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-white/[.08] text-xs">{p.name.split(" ").map(x => x[0]).join("")}</span><div><p className="font-medium">{p.name}</p><p className="text-xs text-zinc-500">{p.department ?? "Unassigned"} · {p.dashboard_access ? "Dashboard access" : "Directory record"}</p></div></div></Card>)}</div> : <State {...q} empty="No people have been synced into the directory."/>}</>; }
function AnalyticsPage() { const { workspaceId } = useWorkspace(); const q = useApi<Insight[]>(workspaceId ? `/workspaces/${workspaceId}/insights` : ""); return <><Header page="analytics"/>{q.data ? <div className="grid gap-4 md:grid-cols-2">{q.data.map(i => <Card key={i.id} className="p-5"><p className="text-sm text-zinc-500">{i.key.replaceAll("_", " ")}</p><p className="mt-3 text-lg font-medium">{String(i.value.value ?? "Insufficient data")}</p><p className="mt-2 text-xs text-emerald-300">{Math.round(i.confidence * 100)}% confidence</p><p className="mt-3 text-xs leading-5 text-zinc-500">{i.explanation}</p></Card>)}</div> : <State {...q} empty="Insights appear after your first weekly report."/>}</>; }
const providers = ["github","slack","google_calendar","microsoft_calendar","jira","linear","notion"] as const;
function IntegrationsPage() { const { workspaceId, me } = useWorkspace(); const q = useApi<Integration[]>(workspaceId ? `/workspaces/${workspaceId}/integrations` : ""); const [busy,setBusy] = useState<string>(); const integrations = q.data ?? []; const connect = async (provider:string) => { if (!workspaceId || !me) return; setBusy(provider); try { const result = await api<{authorization_url:string}>(`/integrations/${provider}/connect?workspace_id=${workspaceId}&user_id=${me.id}&redirect_uri=${encodeURIComponent(`${window.location.origin}/integrations`)}`); window.location.assign(result.authorization_url); } catch (error) { alert(error instanceof Error ? error.message : "Connection failed"); } finally { setBusy(undefined); } }; const disconnect = async (id:string) => { if (!confirm("Disconnect this integration?")) return; await api(`/integrations/${id}`, {method:"DELETE"}); await q.reload(); }; return <><Header page="integrations"/>{q.data ? <div className="grid gap-4 md:grid-cols-2">{providers.map(provider => { const item = integrations.find(x => x.provider === provider); const label = provider.replaceAll("_", " "); return <Card key={provider} className="flex items-center gap-4 p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/[.07] text-sm font-semibold">{label[0].toUpperCase()}</span><div className="flex-1"><p className="font-medium capitalize">{label}</p><p className="mt-1 text-xs text-zinc-500">{item?.state === "connected" ? "Connected and ready" : "Not connected"}</p></div>{item?.state === "connected" ? <Button size="sm" variant="secondary" onClick={() => void disconnect(item.id)}>Disconnect</Button> : <Button size="sm" disabled={busy === provider || !me} onClick={() => void connect(provider)}>{busy === provider ? "Opening…" : "Connect"}</Button>}</Card>; })}</div> : <State {...q} empty="No integrations are configured yet."/>}</>; }
function ReportsPage() { const { workspaceId } = useWorkspace(); const q = useApi<Report[]>(workspaceId ? `/execution/workspaces/${workspaceId}/reports` : ""); const [creating,setCreating] = useState(false); const generate = async () => { setCreating(true); try { await api(`/execution/workspaces/${workspaceId}/reports`, {method:"POST"}); await q.reload(); } finally { setCreating(false); } }; return <><Header page="reports" action={<Button disabled={!workspaceId || creating} onClick={() => void generate()}><RefreshCw size={15}/>{creating ? "Generating…" : "Generate report"}</Button>}/>{q.data ? <div className="grid gap-4">{q.data.map(r => <Card key={r.id} className="flex items-center gap-4 p-5"><FileText className="text-emerald-300"/><div className="flex-1"><p className="font-medium">Weekly execution report</p><p className="mt-1 text-xs text-zinc-500">{new Date(r.period_start).toLocaleDateString()} · Score {r.data.execution_score}</p></div>{r.pdf_url ? <a className="text-sm text-emerald-300" href={r.pdf_url}>Download PDF</a> : <span className="text-xs text-zinc-500">Generating</span>}</Card>)}</div> : <State {...q} empty="No reports have been generated."/>}</>; }
function SettingsPage() { const { workspaceId } = useWorkspace(); const q = useApi<{id:string;name:string;settings:Record<string,unknown>}>(workspaceId ? `/settings/workspaces/${workspaceId}` : ""); const [name,setName] = useState(""); const [saved,setSaved] = useState(false); const save = async () => { if (!q.data) return; await api(`/settings/workspaces/${workspaceId}`, {method:"PATCH",body:JSON.stringify({name:name || q.data.name,settings:q.data.settings})}); setSaved(true); await q.reload(); }; if (!q.data) return <><Header page="settings"/><State {...q} empty="Select a workspace to manage settings."/></>; return <><Header page="settings"/><Card className="max-w-2xl p-5"><p className="font-medium">Workspace profile</p><label className="mt-5 block text-xs text-zinc-400">Workspace name<input value={name || q.data.name} onChange={e => { setName(e.target.value); setSaved(false); }} className="mt-2 h-10 w-full rounded-xl border border-white/10 bg-white/[.04] px-3 text-sm text-white outline-none"/></label><Button className="mt-5" onClick={() => void save()}>Save settings</Button>{saved && <p className="mt-3 text-xs text-emerald-300">Settings saved.</p>}<Link className="mt-6 block text-sm text-emerald-300" href="/approvals">Review extracted task approvals →</Link><Link className="mt-3 block text-sm text-emerald-300" href="/settings/escalations">Configure escalation rules →</Link></Card></>; }
export function WorkspacePage({ page }: { page:"overview"|"meetings"|"tasks"|"people"|"analytics"|"integrations"|"reports"|"settings" }) { const component = {overview:<OverviewPage/>,meetings:<MeetingsPage/>,tasks:<TasksPage/>,people:<PeoplePage/>,analytics:<AnalyticsPage/>,integrations:<IntegrationsPage/>,reports:<ReportsPage/>,settings:<SettingsPage/>}[page]; return <div className="min-h-[calc(100vh-70px)] bg-[radial-gradient(ellipse_at_top_right,rgba(16,185,129,.06),transparent_38%)] p-5 lg:p-8">{component}</div>; }
